# Generated by Django 3.0.4 on 2020-03-09 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('fac_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_vegan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('res_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='')),
                ('open_time', models.TimeField()),
                ('rating', models.FloatField(max_length=255)),
                ('approve_by', models.CharField(max_length=255)),
                ('approve_date', models.DateField(blank=True, null=True)),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.Food')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.Restaurant')),
            ],
        ),
    ]
